{
  "comments": [
    {
      "key": {
        "uuid": "62098982_67a3e4bd",
        "filename": "doctor_tests/main.py",
        "patchSetId": 7
      },
      "lineNbr": 94,
      "author": {
        "id": 1475
      },
      "writtenOn": "2020-01-08T09:06:37Z",
      "side": 1,
      "message": "It will exit directly, do not try once.\nBy the way, here cause another error if the notified_time is none.\nSee: https://build.opnfv.org/ci/job/doctor-verify-fault_management-fuel-sample-x86_64-master/101/console",
      "range": {
        "startLine": 94,
        "startChar": 16,
        "endLine": 94,
        "endChar": 27
      },
      "revId": "d6573e6d65ec8e602abdedb302177c06b615820a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "e18c67d7_209b49d5",
        "filename": "doctor_tests/main.py",
        "patchSetId": 7
      },
      "lineNbr": 94,
      "author": {
        "id": 751
      },
      "writtenOn": "2020-01-08T10:17:12Z",
      "side": 1,
      "message": "Thanks, fixing this",
      "parentUuid": "62098982_67a3e4bd",
      "range": {
        "startLine": 94,
        "startChar": 16,
        "endLine": 94,
        "endChar": 27
      },
      "revId": "d6573e6d65ec8e602abdedb302177c06b615820a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": true
    }
  ]
}